# Python CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - run:
          name: Test the HTML
          command: bash scripts/test/html_proofer_staging.sh
  deploy_prod:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build --config _config.yml,_config_prod.yml
      - run:
          name: Test the HTML
          command: bash scripts/test/html_proofer_prod.sh
      - add_ssh_keys:
          fingerprints:
            - "2d:90:34:fe:cf:bc:ff:42:bc:9f:5d:27:68:88:e8:68"
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/circleci/deploy_prod.sh
  deploy_staging:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - run:
          name: Test the HTML
          command: bash scripts/test/html_proofer_staging.sh
      - add_ssh_keys:
          fingerprints:
            - "d5:5b:77:f9:a8:27:8a:ca:2c:d1:87:7d:ee:df:45:72"
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/circleci/deploy_staging.sh
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - develop
                - gh-pages
  deploy:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only: master
      - deploy_staging:
          filters:
            branches:
              only: develop
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: develop
    jobs:
      - deploy_staging
